// content.jsx — 日英コンテンツ辞書（i18n）
const CONTENT = {
  ja: {
    meta: { dir: "ltr" },
    nav: {
      stance: "スタンス",
      services: "できること",
      proof: "実績",
      flow: "フロー",
      contact: "お問い合わせ",
      cta: "無料で相談する",
      langLabel: "EN",
    },
    hero: {
      eyebrow: "STUDENT DEV & MARKETING COLLECTIVE",
      status: "現在 協力してくださる企業を募集中",
      title_lines: ["AI×学生の爆速実装で、", "御社の『ちょっと面倒』", "解決します。"],
      title_accent: "ちょっと面倒",
      sub: "学生団体Venture Codeの活動・研究プロジェクトの一環として、現在は費用をいただかずに実施しています。アプリ開発からSNS運用まで、現場の課題を丁寧にお手伝いさせていただきます。",
      cta_primary: "相談してみる",
      cta_secondary: "実績を見る",
      terminal_title: "vent_code — zsh — 80×24",
      terminal_lines: [
        { p: "vc@venture-code", cmd: "init --client \"御社\"" },
        { c: "課題をヒアリング中... ████████ done" },
        { c: "解決策を生成... AI app / web / SNS" },
        { p: "vc@venture-code", cmd: "deploy --cost 0" },
        { ok: "shipped in days. 費用: ¥0" },
      ],
      mega: ["BUILD", "FAST", "FREE"],
    },
    stance: {
      eyebrow: "01 / OUR STANCE",
      title: "なぜ、この活動をしているのか",
      lead: "私たちはまだ学びの途中で、経験も多くありません。だからこそ、挑戦させていただける「打席」をください。",
      body: [
        "Venture Codeは、中央大学の文系学生を中心に構成された、ITやAIを学ぶプログラミングサークルです。今、AIの進化が目まぐるしく、これからのAI時代に立ち向かっていくためにも、新しく始まったのがこのプロジェクトです。",
        "あくまで私たちの学びと実績作りのためのプロジェクトですので、費用は一切いただきません。",
        "御社の課題に寄り添い、より良い提案ができるよう全力で貢献させていただきます。まずはぜひ、気軽なご相談から始めてみてください。",
      ],
      pillars: [
        { k: "GIVE FIRST", t: "まず差し出す", d: "私たちの学びと実績作りのため、まずは誠心誠意、貢献させていただきます。" },
        { k: "NO RISK", t: "学生だからこその、気軽さ", d: "あくまで学生団体のプロジェクトの一環です。費用も契約の縛りもありません。" },
        { k: "CASUAL & EASY", t: "現場主義", d: "私たちはプロのコンサルタントではありません。いつでもすぐフットワーク軽く動けます" },
      ],
    },
    services: {
      eyebrow: "02 / WHAT WE DO",
      title: "私たちができること。",
      lead: "そして、口だけではないことの証拠を3つ。",
      proof_label: "証拠",
      items: [
        {
          no: "01",
          tag: "AI APP DEV",
          title: "現場特化型のAIアプリ開発・提供",
          desc: "現場の業務フローに合わせて、必要なツールをAIで素早く実装。紙やExcelの手作業をデジタルに置き換えます。",
          proof: "営業現場のKPI管理アプリをAIで爆速開発。紙管理をなくし、毎日およそ1,000件のデータ入力をデジタル化して事務負担を大幅に削減しました。",
        },
        {
          no: "02",
          tag: "WEB / PLATFORM",
          title: "AIを活用したWeb・プラットフォーム構築",
          desc: "コーポレートサイトから業務用プラットフォームまで、AIツールを活用して短期間で構築します。",
          proof: "いま御覧いただいているこの公式サイトも、AIツールを活用して数日で構築したものです。スピードと品質の両立を、このページ自体で証明しています。",
        },
        {
          no: "03",
          tag: "SNS / MARKETING",
          title: "Instagram運用・SNSマーケティング支援",
          desc: "現役大学生のリアルなトレンド感覚で、アカウント設計から運用までを支援します。",
          proof: "当団体 Venture Code の公式Instagramを、現役大学生の感覚で自社運用中。若者向けの訴求やアカウント設計のノウハウを、そのまま御社へ還元します。",
        },
      ],
    },
    flow: {
      eyebrow: "03 / HOW IT WORKS",
      title: "ご相談から、提供まで。",
      lead: "やることはシンプル。3ステップで、御社の『面倒』が片付きます。",
      steps: [
        { no: "STEP 1", t: "気軽な相談", d: "まずは「ここ変えたいんだよね」というお話を、雑談ベースで気楽にお聞かせください。かしこまった準備は一切いりません。" },
        { no: "STEP 2", t: "サクッと形にする", d: "最新のAIを使いながら、まずは「こんなのどうですか？」という簡単な試作品やアイデアをお見せします。" },
        { no: "STEP 3", t: "よかったら、使ってみる", d: "実際の現場で使ってみていただきながら、使いやすいように一緒に整えていきます。" },
      ],
    },
    contact: {
      eyebrow: "04 / GET STARTED",
      title: "まずは、雑な相談から。",
      lead: "簡単のひと言でOKです。費用はかかりません。",
      fields: {
        company: "会社名 / 団体名",
        name: "ご担当者名",
        email: "メールアドレス",
        category: "ご相談内容",
        message: "課題・ご相談（ざっくりで大丈夫です）",
      },
      categories: ["AIアプリ開発", "Web・サイト構築", "SNS・Instagram運用", "まだ決まっていない / その他"],
      placeholder: {
        company: "株式会社ベンチャーコード",
        name: "山田 太郎",
        email: "you@example.com",
        message: "例：毎日の日報を紙で集計していて、月末がとにかく面倒…",
      },
      submit: "無料で相談を送る",
      note: "※ このフォームは見た目のデモです。送信処理は実装予定です。",
      success: "送信されました（デモ）。実際の受付は近日公開します。",
    },
    footer: {
      tagline: "AIと学生の力で、現場の『面倒』を片付ける。",
      built: "このサイトはAIツールを活用して数日で構築されました。",
      contact_label: "CONTACT",
      sns_label: "SOCIAL",
      copyright: "© 2026 Venture Code. Student dev collective.",
      nav_label: "INDEX",
    },
  },

  en: {
    meta: { dir: "ltr" },
    nav: {
      stance: "Stance",
      services: "What we do",
      proof: "Proof",
      flow: "Flow",
      contact: "Contact",
      cta: "Get a free consult",
      langLabel: "日本語",
    },
    hero: {
      eyebrow: "STUDENT DEV & MARKETING COLLECTIVE",
      status: "Now taking projects — at $0",
      title_lines: ["AI + students, shipping fast.", "We fix the little frictions", "slowing your business."],
      title_accent: "little frictions",
      sub: "Completely free. From internal tools to social media ops, we take on the real problems on your floor.",
      cta_primary: "Get a free consult",
      cta_secondary: "See the proof",
      terminal_title: "vent_code — zsh — 80×24",
      terminal_lines: [
        { p: "vc@venture-code", cmd: "init --client \"your team\"" },
        { c: "listening to the problem... ████████ done" },
        { c: "generating solution... AI app / web / SNS" },
        { p: "vc@venture-code", cmd: "deploy --cost 0" },
        { ok: "shipped in days. cost: $0" },
      ],
      mega: ["BUILD", "FAST", "FREE"],
    },
    stance: {
      eyebrow: "01 / OUR STANCE",
      title: "Why it's completely free.",
      lead: "We're students — short on experience. So instead of money, give us at-bats.",
      body: [
        "Venture Code is a student collective that uses AI to help companies streamline operations and grow on social. To prove ourselves, we do everything — from listening to your problems to delivering the fix — completely free.",
        "What we want in return isn't a fee. It's real problems from a real floor, and the chance to solve them. We show up in person, abuse AI and trends, and ship in days.",
        "No risk, give-first. So bring us your messiest, most unreasonable request.",
      ],
      pillars: [
        { k: "GIVE FIRST", t: "Give first", d: "Zero fee. We deliver value up front and earn trust." },
        { k: "NO RISK", t: "No risk", d: "No cost, no lock-in. Walk away anytime if it's not a fit." },
        { k: "ON THE GROUND", t: "On the ground", d: "We show up in person to feel the friction firsthand." },
      ],
    },
    services: {
      eyebrow: "02 / WHAT WE DO",
      title: "What we can build.",
      lead: "And three pieces of proof that it's not just talk.",
      proof_label: "PROOF",
      items: [
        {
          no: "01",
          tag: "AI APP DEV",
          title: "Field-specific AI app development",
          desc: "We build the exact tool your workflow needs with AI — replacing paper and manual Excel work with something digital.",
          proof: "We rapidly built an AI-powered KPI tracker for a sales floor. It killed the paper process and digitized roughly 1,000 data entries a day, sharply cutting admin load.",
        },
        {
          no: "02",
          tag: "WEB / PLATFORM",
          title: "AI-built websites & platforms",
          desc: "From corporate sites to internal platforms, we use AI tooling to ship in a short window.",
          proof: "The very site you're reading was built in a few days with AI tooling. Speed and quality, proven by this page itself.",
        },
        {
          no: "03",
          tag: "SNS / MARKETING",
          title: "Instagram & social marketing",
          desc: "With the real trend instincts of current students, we help from account strategy through day-to-day ops.",
          proof: "We run Venture Code's own Instagram in-house with a student's instinct for what lands. We hand that account-design know-how straight back to you.",
        },
      ],
    },
    flow: {
      eyebrow: "03 / HOW IT WORKS",
      title: "From hello to handover.",
      lead: "Simple. Three steps and your friction is gone.",
      steps: [
        { no: "STEP 1", t: "Listen", d: "We visit your floor and map out what's tedious and where time leaks." },
        { no: "STEP 2", t: "Ship fast", d: "Abusing AI, we turn an app, site, or plan into something real in days." },
        { no: "STEP 3", t: "Deliver free", d: "Delivered at zero cost. We'll stay on for ops and iteration if you want." },
      ],
    },
    contact: {
      eyebrow: "04 / GET STARTED",
      title: "Start with a rough idea.",
      lead: "\"Can you do this?\" is enough. It costs nothing.",
      fields: {
        company: "Company / Team",
        name: "Your name",
        email: "Email",
        category: "Topic",
        message: "Your problem or idea (rough is fine)",
      },
      categories: ["AI app development", "Web / site build", "Social / Instagram ops", "Not sure yet / other"],
      placeholder: {
        company: "Venture Code Inc.",
        name: "Jane Doe",
        email: "you@example.com",
        message: "e.g. We tally daily reports on paper and month-end is a nightmare…",
      },
      submit: "Send a free consult",
      note: "* This form is a visual demo. Submission will be wired up later.",
      success: "Sent (demo). Real intake goes live soon.",
    },
    footer: {
      tagline: "Students + AI, clearing the friction on your floor.",
      built: "This site was built in a few days using AI tooling.",
      contact_label: "CONTACT",
      sns_label: "SOCIAL",
      copyright: "© 2026 Venture Code. Student dev collective.",
      nav_label: "INDEX",
    },
  },
};

window.CONTENT = CONTENT;
